---
title: "Ranking the Best Shooters and Goalies in the NHL"
subtitle: "Rankings Based on Total Expected Goals and Expected Saves from 2016-2023"
author: "Devin Basley"
date: "2024-02-13"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(hockeyR)
library(tidyverse)

```


## Data Cleaning

```{r}


hockey_shot_2023 <- load_pbp(2023)
hockey_shot_2022 <- load_pbp(2022)
hockey_shot_2021 <- load_pbp(2021)
hockey_shot_2020 <- load_pbp(2020)
hockey_shot_2019 <- load_pbp(2019)
hockey_shot_2018 <- load_pbp(2018)
hockey_shot_2017 <- load_pbp(2017)
hockey_shot_2016 <- load_pbp(2016)






# List of data frame names
data_frame_names <- c("hockey_shot_2016", "hockey_shot_2017", "hockey_shot_2018", 
                      "hockey_shot_2019", "hockey_shot_2020", "hockey_shot_2021",
                      "hockey_shot_2022", "hockey_shot_2023")

```


```{r}
# List to store filtered and modified data frames
filtered_data_frames <- list()

# Loop through each data frame
for (df_name in data_frame_names) {
  # Filter and modify each data frame
  filtered_df <- get(df_name) %>%
    filter(event_type %in% c("SHOT", "MISSED_SHOT", "GOAL", "BLOCKED_SHOT")) %>%
    dplyr::select(game_id, description, event_type, period, period_seconds_remaining,
                  game_seconds_remaining, home_score, away_score, home_name, 
                  away_name, event_team, event_goalie_name, empty_net,
                  event_player_1_name, event_player_1_type,
                  event_player_2_name, event_player_2_type,
                  strength_code, x_fixed, y_fixed, shot_distance, shot_angle, season) %>%
    rename(shot_outcome = event_type)
  
  # Store filtered data frame in the list
  filtered_data_frames[[df_name]] <- filtered_df
}

# Combine all filtered data frames into one data set
all_hockey_shots <- bind_rows(filtered_data_frames)


all_hockey_shots <- all_hockey_shots %>%
  # Remove shots where distance is missing
  filter(!is.na(shot_distance), 
         # Remove missed shots where goalie is missing:
         !is.na(event_goalie_name),
         # Only consider even-strength
         strength_code == "EV",
         # Remove empty-net
         (is.na(empty_net) | empty_net == FALSE)) %>%
  # Create numeric indicator for goals:
  mutate(is_goal = as.numeric(shot_outcome == "GOAL"),
         # Get the goalie team:
         goalie_team = ifelse(event_team == home_name,
                              away_name, home_name)) %>%
  # Just grab a subset of columns:
  dplyr::select(game_id, period,
                event_player_1_name, event_team, event_goalie_name,
                goalie_team, x_fixed, y_fixed, shot_distance,
                shot_angle, is_goal) %>%
  rename(shooting_player = event_player_1_name,
         shooting_team = event_team, 
         goalie_name = event_goalie_name)

all_hockey_shots$shooting_player <- as.factor(all_hockey_shots$shooting_player)
all_hockey_shots$goalie_name <- as.factor(all_hockey_shots$goalie_name)

```


## xGoals by logistic regression

```{r}

xG_logit <- glm(is_goal ~ shot_distance + shot_angle,
                family = "binomial",
                data = all_hockey_shots)

summary(xG_logit)


```


## xGoals by multi-level model

```{r}

library(lme4)

xG_multi <- glmer(is_goal ~ shot_distance + shot_angle +
                    (1 | shooting_player) + (1 | goalie_name),
                  family = "binomial",
                  data = all_hockey_shots)

summary(xG_multi)


```



## Calculate Player Total xGoals

```{r}


# Predict expected goals for each shot
expected_goals <- predict(xG_multi, newdata = all_hockey_shots, type = "response")

# Add predicted expected goals to your data
all_hockey_shots$expected_goals <- expected_goals
all_hockey_shots$expected_save <- (1-expected_goals)

# Sum up expected goals for each shooter
shooter_expected_goals <- aggregate(expected_goals ~ shooting_player, data = all_hockey_shots, FUN = sum)
goalie_expected_saves <- aggregate(expected_save ~ goalie_name, data = all_hockey_shots, FUN = sum)



# Rank shooters based on total expected goals
best_shooters <- shooter_expected_goals[order(shooter_expected_goals$expected_goals, decreasing = TRUE), ]
best_goalies <- goalie_expected_saves[order(goalie_expected_saves$expected_save, decreasing = TRUE), ]




```


## Best Shooters


```{r}
best_shooters %>%
  top_n(10) %>%
  ggplot(aes(reorder(x = shooting_player, expected_goals), y = expected_goals)) +
  geom_col() +
  coord_flip() +
  labs(x = "Shooter",
       y = "Total Expected Goals",
       title = "Best Shooters from 2016-2023") +
  theme_bw()

```

## Best Goalies

```{r}
best_goalies %>%
  top_n(10) %>%
  ggplot(aes(reorder(x = goalie_name, expected_save), y = expected_save)) +
  geom_col() +
  coord_flip() +
  labs(x = "Goalie",
       y = "Total Expected Saves",
       title = "Best Goalies from 2016-2023") +
  theme_bw()

```